name: Build

on: 
  push:
jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: package
      run: bash script/package-with-ocra.sh
    # - name: Set up environment
    #   run: cd packaging && bundle install
    # - name: Install ocran
    #   run: gem install ocran
    # - name: Build
    #   run: |
    #     ocran pact-broker.rb \
    #       ca-bundle.crt \
    #       --verbose \
    #       --output pact-broker-cli.exe \
    #       --gem-all \
    #       --add-all-core \
    #       --gem-full=openssl \
    #       --dll ruby_builtin_dlls/zlib1.dll \
    #       --dll ruby_builtin_dlls/libgmp-10.dll \
    #       --dll ruby_builtin_dlls/libyaml-0-2.dll \
    #       --dll ruby_builtin_dlls/libssl-3-x64.dll \
    #       --dll ruby_builtin_dlls/libcrypto-3-x64.dll
    - name: Show ocran build output
      run: ls pkg
    - name: Run ocran build output
      run: .\packaging\pact-broker-cli.exe
    - name: Upload pact-
      uses: actions/upload-artifact@v3
      with:
        name: pact
        path: pkg
  test:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - run: ls pact
    - run: cd pact
    - run: gunzip pact.gz
    - run: ls pact
    - run: gunzip pact\pact-broker-cli.exe.gz
    - run: ls pact
    - run: ls
    - run: .\pact\pact-broker-cli.exe